#!/bin/sh

set -eu

package_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

exec "$package_dir/runtime/ld-linux-x86-64.so.2" \
  --inhibit-cache \
  --library-path "$package_dir/runtime" \
  "$package_dir/postui.bin" \
  --config "$package_dir/config.yaml" \
  "$@"
